title: Nicolette Mtisi
logo: /portfolio/profile.png
description: Data-Driven Solutions, Tailored for Tomorrow. Passionate AI Engineer & Data Scientist.
show_downloads: false
theme: jekyll-theme-cayman
